typography_spectrum: 0.5535973773803562
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.3378735922742635
  lightness: 0.7700412010308355
  saturation: 0.8202064796350896
  rhythmicContrast: 0.5204018584918231
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4746808304917067
analytics:
  google: null
  facebook: null
  twitter: null
name: Elevanna
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Elevanna
description: Optimiza tu rendimiento!
purpose: []
